COMPONENT=TestHomeCommC
CFLAGS=-I/home/chuka/projects/puppet-os/system/\
-L/home/chuka/projects/puppet-os/system/\
-I/home/chuka/projects/puppet-os/interfaces/\
-I/usr/local/lib/puppet/c/\
-I/usr/local/lib/puppet/c/\
-I$(TOSDIR)/lib/net/\
-I$(TOSDIR)/lib/net/ctp

include $(MAKERULES)

